on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix flake check
      - run: nix fmt
      - run: |
          nix fmt
          if [[ $(git diff --stat) != '' ]]; then
            git add -A
            git commit -m 'nix fmt'
            git push origin ${GITHUB_REF#refs/heads/}
          fi
