on: push
jobs:
  test:
    runs-on: nixpkgs/nix-flakes
    steps:
      - run: nix flake check
      - run: nix fmt
      - run: |
          nix fmt
          if [[ $(git diff --stat) != '' ]]; then
            git add -A
            git commit -m 'nix fmt'
            git push origin ${GITHUB_REF#refs/heads/}
          fi
